baseurl = "http://everttimberg.io/"
languageCode = "en-us"
theme = "evinson"
title = "Evert Timberg"

[params]
	author = "Evert Timberg"
	title = "Evert Timberg"
	subtitle = "Software developer"
	mainImagePath = "/images/main_profile_pic_thumb.png"

[menu]
	# Items shown on home page
	[[menu.main]]
		url = "/about/"
		name = "About"
		Weight = 0
		Identifier = "about"
	[[menu.main]]
		url = "/project/"
		name = "Projects"
		Weight = 1
		Identifier = "projects"
	[[menu.main]]
		url = "/album/"
		name = "Photography"
		Weight = 2
		Identifier = "photography"
	[[menu.main]]
		url = "/post/"
		name = "Blog"
		Weight = 3
		Identifier = "blog"
	
	# Side menu
	[[menu.side]]
		name = "About"
		url = "/about/"
		Weight = 0

	[[menu.side]]
		name = "Projects"
		url = "/project/"
		Weight = 1

	[[menu.side]]
		name = "Photography"
		url = "/album/"
		Weight = 2
		Identifier = "photography"

	[[menu.side]]
		name = "Blog"
		url = "/post/"
		Weight = 3

# Social Media Links
[Social]
	github = "etimberg"
	linkedin = "etimberg"
	twitter = "EvertTimberg"
